import { defineField, defineType } from "sanity";

export const homePage = defineType({
  name: "homePage",
  title: "Home Page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "about", title: "About blurb" },
    { name: "values", title: "Why choose us" },
    { name: "featured", title: "Featured content" },
    { name: "cta", title: "Closing CTA" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Eyebrow",
      type: "string",
      group: "hero",
      description: "Small line above the headline (e.g. company name).",
    }),
    defineField({
      name: "heroTitle",
      title: "Headline",
      type: "string",
      group: "hero",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "heroSubtitle",
      title: "Subheading",
      type: "text",
      rows: 2,
      group: "hero",
    }),
    defineField({
      name: "heroImage",
      title: "Hero background image",
      type: "imageWithAlt",
      group: "hero",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "heroPrimaryCta",
      title: "Primary CTA",
      type: "cta",
      group: "hero",
    }),
    defineField({
      name: "heroSecondaryCta",
      title: "Secondary CTA",
      type: "cta",
      group: "hero",
    }),
    defineField({
      name: "aboutTitle",
      title: "About title",
      type: "string",
      group: "about",
    }),
    defineField({
      name: "aboutBody",
      title: "About body",
      type: "array",
      of: [{ type: "block" }],
      group: "about",
    }),
    defineField({
      name: "aboutImages",
      title: "About images",
      type: "array",
      of: [{ type: "imageWithAlt" }],
      group: "about",
      validation: (Rule) => Rule.max(3),
    }),
    defineField({
      name: "valuesTitle",
      title: "Section title",
      type: "string",
      initialValue: "Why choose Solemn Oath?",
      group: "values",
    }),
    defineField({
      name: "values",
      title: "Value cards",
      type: "array",
      group: "values",
      of: [
        {
          type: "object",
          fields: [
            { name: "icon", type: "string", description: "lucide-react icon name." },
            { name: "title", type: "string", validation: (Rule) => Rule.required() },
            { name: "description", type: "text", rows: 3 },
          ],
        },
      ],
      validation: (Rule) => Rule.max(4),
    }),
    defineField({
      name: "featuredServicesTitle",
      title: "Featured services title",
      type: "string",
      initialValue: "Services",
      group: "featured",
    }),
    defineField({
      name: "featuredServices",
      title: "Featured services",
      type: "array",
      of: [{ type: "reference", to: [{ type: "service" }] }],
      group: "featured",
      validation: (Rule) => Rule.max(4),
    }),
    defineField({
      name: "featuredProjectsTitle",
      title: "Featured projects title",
      type: "string",
      initialValue: "Recent transformations",
      group: "featured",
    }),
    defineField({
      name: "ctaTitle",
      title: "Closing CTA title",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaSubtitle",
      title: "Closing CTA subtitle",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaButton",
      title: "Closing CTA button",
      type: "cta",
      group: "cta",
    }),
    defineField({ name: "seo", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Home Page" }) },
});
